# Default values for pma.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: phpmyadmin
  pullPolicy: IfNotPresent
  tag: "5.2.1-apache"

database:
  serverUrl: "c-c9qj8t52ls855e6ua0gb.rw.mdb.yandexcloud.net"
