{
 "title": "VP Board",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage, %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",job=\"nodeexporter\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "CPULA 1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "CPULA 5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "CPULA 15"
    }
   ]
  },
  {
   "title": "Free RAM %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{job=\"nodeexporter\"} / node_memory_MemTotal_bytes{job=\"nodeexporter\"}) * 100"
    }
   ]
  },
  {
   "title": "Free disk space %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{job=\"nodeexporter\",fstype!~\"vfat|tmpfs|ramfs\"} / node_filesystem_size_bytes{job=\"nodeexporter\",fstype!~\"vfat|tmpfs|ramfs\"}) * 100"
    }
   ]
  },
  {
   "title": "Free RAM GB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"} / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Free disk GB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"nodeexporter\",fstype!~\"ramfs|tmpfs|vfat\"} / 1024 / 1024 / 1024"
    }
   ]
  }
 ]
}