#apiVersion: v1
#kind: Service
#metadata:
#  name: pma-service
#spec:
#  selector:
#    app: pma
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80


apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  ports:
  # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
  - port: 80
    name: plaintext
    # Порт контейнера, на котором доступно приложение.
    targetPort: 80
  # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: pma
  type: LoadBalancer