version: '3.1'

networks:
  postgresnet:
    driver: bridge

volumes:
  database_data: {}
  backups_data: {}

services:
  postgres:
    image: postgres:12
    container_name: postgresvp32
    volumes:
      - database_data:/var/lib/postgresql/data
      - backups_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - postgresnet
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres

