apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: echo
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080
      name: web-port
---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: echo
  ports:
  - name: netology-svc-port
    port: 80
    targetPort: web-port