apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: task2-ds
  labels:
    app: task2
spec:
  selector:
    matchLabels:
      app: task2
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: varsyslog
          mountPath: /output/logs
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
      volumes:
      - name: varsyslog
        hostPath:
          path: /var/log/syslog