apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-readlog-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-readlog-rb
subjects:
- kind: User
  name: podwatcher
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-readlog-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool

