apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deployment
  labels:
    app: task2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task2
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
---
apiVersion: v1
kind: Service
metadata:
  name: task2-svc
spec:
  selector:
    app: task2
  ports:
  - name: task2-nginx-svc-port
    port: 9001
    targetPort: 80
  - name: task2-multitool-svc-port
    port: 9002
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: task2-np-svc
spec:
  selector:
    app: task2
  ports:
  - name: task2-nginx-np-svc-port
    protocol: TCP
    nodePort: 30000
    port: 80
  - name: task2-multitool-np-svc-port
    protocol: TCP
    port: 8080
    nodePort: 30001
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: outer-pod
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    ports:
    - containerPort: 8080
