all:
  hosts:
    master1:
      ansible_host: 84.201.170.180
      ansible_user: yc-user
      ip: 192.168.0.11
      access_ip: 192.168.0.11
    master2:
      ansible_host: 84.201.169.232
      ansible_user: yc-user
      ip: 192.168.0.17
      access_ip: 192.168.0.17
    master3:
      ansible_host: 84.201.181.17
      ansible_user: yc-user
      ip: 192.168.0.33
      access_ip: 192.168.0.33
    node1:
      ansible_host: 84.201.180.215
      ansible_user: yc-user
      ip: 192.168.0.22
      access_ip: 192.168.0.22
    node2:
      ansible_host: 84.201.181.183
      ansible_user: yc-user
      ip: 192.168.0.21
      access_ip: 192.168.0.21
    node3:
      ansible_host: 84.201.181.162
      ansible_user: yc-user
      ip: 192.168.0.6
      access_ip: 192.168.0.6
    node4:
      ansible_host: 84.201.181.120
      ansible_user: yc-user
      ip: 192.168.0.25
      access_ip: 192.168.0.25
  children:
    kube_control_plane:
      hosts:
        master1:
        master2:
        master3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        master1:
        master2:
        master3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
