apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-deployment
  labels:
    app: task1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task1
  template:
    metadata:
      labels:
        app: task1
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'while true; do echo Hello world $(date)! >> /output/output.txt; sleep 5; done']
        volumeMounts:
        - name: task1-volume
          mountPath: /output
      - name: multitool
        image: wbitt/network-multitool
        ports:
        volumeMounts:
        - name: task1-volume
          mountPath: /input
      volumes:
      - name: task1-volume
        persistentVolumeClaim:
          claimName: pvc-vol
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 512Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: host-path
  hostPath:
    path: /data/pv1
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol
spec:
  volumeMode: Filesystem
  storageClassName: host-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
